# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_mi <- function(datax, datay, k) {
    .Call(`_fastmit_knn_mi`, datax, datay, k)
}

mi_test <- function(datax, datay, k, perm_num, ini_mi) {
    .Call(`_fastmit_mi_test`, datax, datay, k, perm_num, ini_mi)
}

